name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t urlshortener .

      - name: Tag Docker image
        run: |
          docker tag urlshortener:latest \
            816352410007.dkr.ecr.eu-north-1.amazonaws.com/urlshortener:latest

      - name: Push Docker image
        run: |
          docker push \
            816352410007.dkr.ecr.eu-north-1.amazonaws.com/urlshortener:latest

      - name: Configure SSH
        run: |
          mkdir -p "$HOME/.ssh"
          printf '%s\n' "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > "$HOME/.ssh/urlshortener-key.pem"
          chmod 600 "$HOME/.ssh/urlshortener-key.pem"
          ssh-keyscan -H 13.51.233.43 >> "$HOME/.ssh/known_hosts"
          ssh-keyscan -H 13.60.183.169 >> "$HOME/.ssh/known_hosts"
          
      - name: Test SSH to EC2 instances
        run: |
          ssh -i ~/.ssh/urlshortener-key.pem ubuntu@13.51.233.43 "echo EC2-1-SSH-OK"
          ssh -i ~/.ssh/urlshortener-key.pem ubuntu@13.60.183.169 "echo EC2-2-SSH-OK"